--DELETE FROM [ACCOUNT]
INSERT INTO ACCOUNT (ACCOUNTID, ACCOUNTNAME, BALANCE) VALUES (1, 'Default', 300.0)
INSERT INTO ACCOUNT (ACCOUNTID, ACCOUNTNAME, BALANCE) VALUES (2, 'Default', 300.0)
INSERT INTO ACCOUNT (ACCOUNTID, ACCOUNTNAME, BALANCE) VALUES (3, 'Default', 300.0)
INSERT INTO ACCOUNT (ACCOUNTID, ACCOUNTNAME, BALANCE) VALUES (4, 'Default', 300.0)
INSERT INTO ACCOUNT (ACCOUNTID, ACCOUNTNAME, BALANCE) VALUES (5, 'Default', 300.0)
INSERT INTO ACCOUNT (ACCOUNTID, ACCOUNTNAME, BALANCE) VALUES (6, 'Default', 300.0)

--DELETE FROM USER
INSERT INTO USER (USERID, USERNAME, ACCOUNTID) VALUES (1, 'Bill', 1)
INSERT INTO USER (USERID, USERNAME, ACCOUNTID) VALUES (2, 'Fill', 2)
INSERT INTO USER (USERID, USERNAME, ACCOUNTID) VALUES (3, 'Lill', 3)
INSERT INTO USER (USERID, USERNAME, ACCOUNTID) VALUES (4, 'Gill', 4)
INSERT INTO USER (USERID, USERNAME, ACCOUNTID) VALUES (5, 'Will', 5)
INSERT INTO USER (USERID, USERNAME, ACCOUNTID) VALUES (6, 'Zill', 6)